version: '3.8'

services:
  whatsapp:
    build: .
    command: node whatsapp-simple.js
    ports:
      - "${WHATSAPP_PORT:-3000}:${WHATSAPP_PORT:-3000}"
    environment:
      - WHATSAPP_PORT=${WHATSAPP_PORT:-3000}
      - WHATSAPP_HOST=${WHATSAPP_HOST:-0.0.0.0}
      - BACKEND_URL=http://backend:${BACKEND_PORT:-8000}
      - SALON_NAME=${SALON_NAME:-Beauty Salon}
      - DOCKER_ENV=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: .
    command: python -m uvicorn app.main_simple:app --host 0.0.0.0 --port ${BACKEND_PORT:-8000}
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - BACKEND_HOST=${BACKEND_HOST:-0.0.0.0}
      - WHATSAPP_SERVICE_URL=http://whatsapp:${WHATSAPP_PORT:-3000}
      - SALON_NAME=${SALON_NAME:-Beauty Salon}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-appointment-booking-4c50f}
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-key.json
      - DOCKER_ENV=true
    volumes:
      - ./firebase-key.json:/app/firebase-key.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    name: whatsapp-booking-network 