version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-booking-bot
    ports:
      - "3000:3000"  # WhatsApp service
      - "8000:8000"  # Backend API
    environment:
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome-stable
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - NODE_ENV=production
    volumes:
      # Mount Firebase credentials (make sure firebase-key.json exists)
      - ./firebase-key.json:/app/firebase-key.json:ro
      # Persist WhatsApp session data
      - whatsapp_auth:/app/.wwebjs_auth
      - whatsapp_cache:/app/.wwebjs_cache
      - whatsapp_tokens:/app/tokens
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp_auth:
  whatsapp_cache:
  whatsapp_tokens: 