[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
ACTIVE_SALON = "salon_c"
QR_ONLY_MODE = "true"
PYTHON_VERSION = "3.11" 